version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-replica
    ports:
      - "27017:27017"
    volumes:
      - ./db-volume/mongo-replica:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./mongo-keyfile:/etc/mongo-keyfile
    entrypoint: ["mongod", "--config", "/etc/mongod.conf"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}